<?php
/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>

<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Company')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?= $block->escapeHtml(__('Creating a comapny account to access b2b purchases.')) ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getUrl('company/account/create')) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create a Company Account')) ?></span></a>
            </div>
        </div>
    </div>
    
    <?= $block->getChildHtml('customer.link.new') ?>
</div>

