<?php
/**
 * This file is part of the Orangecat Company package.
 *
 * (c) Oliverio Gombert <olivertar@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

use Orangecat\Company\Block\Account\CompanyRegisterLink;
use Magento\Framework\Escaper;

/** @var CompanyRegisterLink $block */
/** @var Escaper $escaper */

$label = $block->getLabel() ?: __('Create a Company');
?>
<li class="link company-register-link">
    <a href="<?= $escaper->escapeUrl($block->getHref()) ?>">
        <?= $escaper->escapeHtml($label) ?>
    </a>
</li>
