<?php

/** @var \Orangecat\Company\Block\Adminhtml\Edit\Tab\Role $block */
?>
<div class="admin__field field field-role_id">
    <label class="label admin__field-label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId()) ?>">
        <span><?= $escaper->escapeHtml(__('Company Role')) ?></span>
    </label>
    <div class="admin__field-control control">
        <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId()) ?>"
            name="<?= $escaper->escapeHtmlAttr($block->getFieldName()) ?>"
            data-form-part="customer_form"
            class="admin__control-select">
            <option value=""><?= $escaper->escapeHtml(__('Select a Role')) ?></option>
            <?php foreach ($block->getOptions() as $option): ?>
                <option value="<?= $escaper->escapeHtmlAttr($option['value']) ?>"
                    <?= $option['value'] == $block->getCurrentRoleId() ? 'selected="selected"' : '' ?>>
                    <?= $escaper->escapeHtml($option['label']) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<input type="hidden" name="customer[company_tab_loaded]" value="1" data-form-part="customer_form" />
<br />